### ISSUE TITLE
云函数部署

### ISSUE THREAD

**Issue by MarcelloLH** [DoveBoy/jd_scripts#3]
能否请教下这个ac的云函数怎么操作

**Comment by DoveBoy** [comment]
@MarcelloLH ac部署云函数不做讨论，repo已有详细教程，请仔细阅读

**Comment by MarcelloLH** [comment]
> @MarcelloLH ac部署云函数不做讨论，repo已有详细教程，请仔细阅读

麻烦告知在哪里?

**Comment by DoveBoy** [comment]
@MarcelloLH 已经说得很明白了，repo下自行查找
